# 通用配置
#

# 服务器类型，可选值有：
#   grpc：启动一个 gRPC 服务器
#   grpc-gateway: 启动一个 gRPC 服务器 + HTTP 反向代理服务器
#   gin：基于 gin 框架启动一个 HTTP 服务器
# 服务器模式选择：
#   - 应用内调用选择 grpc
#   - 如果有外部服务调用选择 grpc-gateway
#   - 学习 Gin 框架时选择 gin
server-mode: grpc-gateway
# JWT 签发密钥
jwt-key: Vnk8GRhFEz7uD3mltQOBPZZLXiLJZNVjhT81sKpnzIuMf2
# JWT Token 过期时间
expiration: 4h
# 指示是否启用内存数据库（用于测试或开发环境）.
# 如果设置为 true 则忽略 mysql 配置.
enable-memory-store: true

# 安全服务器相关配置
tls:
  # 是否启动 HTTPS 安全服务器
  # 生产环境建议开启 HTTPS。并使用 HTTPS 协议访问 API 接口
  use-tls: true
  # 证书
  cert: _output/cert/server.crt
  # 证书 Key 文件
  key: _output/cert/server.key

# HTTP 服务器相关配置
http:
  # HTTP 服务器监听地址
  addr: :5555

# GRPC 服务器相关配置
grpc:
  # GRPC 服务器监听地址
  addr: :6666

# 日志配置
log:
  # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-caller: false
  # 是否禁止在 panic 及以上级别打印堆栈信息
  disable-stacktrace: false
  # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  # 生产环境建议设置为 info
  level: debug
  # 指定日志显示格式，可选值：console, json
  # 生产环境建议设置为 json
  format: json
  # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出
  output-paths: [stdout]